# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/kingk/Downloads/stopwatch.xdc

# Block Designs: bd/stopwatch_system/stopwatch_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_system || ORIG_REF_NAME==stopwatch_system}]

# IP: bd/stopwatch_system/ip/stopwatch_system_stopwatch_controller_0_0/stopwatch_system_stopwatch_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_system_stopwatch_controller_0_0 || ORIG_REF_NAME==stopwatch_system_stopwatch_controller_0_0}]

# IP: bd/stopwatch_system/ip/stopwatch_system_processing_system7_0_0/stopwatch_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_system_processing_system7_0_0 || ORIG_REF_NAME==stopwatch_system_processing_system7_0_0}]

# IP: bd/stopwatch_system/ip/stopwatch_system_ps7_0_axi_periph_0/stopwatch_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==stopwatch_system_ps7_0_axi_periph_0}]

# IP: bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==stopwatch_system_rst_ps7_0_50M_0}]

# IP: bd/stopwatch_system/ip/stopwatch_system_auto_pc_0/stopwatch_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stopwatch_system_auto_pc_0 || ORIG_REF_NAME==stopwatch_system_auto_pc_0}]

# XDC: bd/stopwatch_system/stopwatch_system_ooc.xdc
