# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0.xci
# IP: The module: 'stopwatch_system_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'stopwatch_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'stopwatch_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stopwatch_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0.xci
# IP: The module: 'stopwatch_system_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'stopwatch_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'stopwatch_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/CENG3430/Lab07/Lab07.srcs/sources_1/bd/stopwatch_system/ip/stopwatch_system_rst_ps7_0_50M_0/stopwatch_system_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stopwatch_system_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
