# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CENG3430/Lab09_1/Lab09_1.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0.xci
# IP: The module: 'system_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CENG3430/Lab09_1/Lab09_1.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/CENG3430/Lab09_1/Lab09_1.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/CENG3430/Lab09_1/Lab09_1.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0.xci
# IP: The module: 'system_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CENG3430/Lab09_1/Lab09_1.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/CENG3430/Lab09_1/Lab09_1.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
